version: "3.9"

services:

  pedidos:
    build: ./services/pedidos
    container_name: pedidos
    ports:
      - "5001:5000"

  pagamentos:
    build: ./services/pagamentos
    container_name: pagamentos
    ports:
      - "5002:5000"

  estoque:
    build: ./services/estoque
    container_name: estoque
    ports:
      - "5003:5000"

  gateway:
    build: ./services/gateway
    container_name: gateway
    depends_on:
      - pedidos
      - pagamentos
      - estoque
    ports:
      - "8080:5000"
